version: '3'
services:
  blog-nginx:
    build:
      context: ./blog/docker/development
      dockerfile: nginx.docker
    volumes:
      - ./blog:/app
    depends_on:
      - blog-php-fpm
    ports:
      - "8080:80"
  blog-php-fpm:
    build:
      context: ./blog/docker/development
      dockerfile: php-fpm.docker
    volumes:
      - ./blog:/app
    depends_on:
      - blog-postgres
      - blog-redis
      - blog-queue-redis
      - storage
      - mailer
      - centrifugo
  blog-php-cli:
    build:
      context: ./blog/docker/development
      dockerfile: php-cli.docker
    volumes:
      - ./blog:/app
      - composer:/root/.composer/cache
    depends_on:
      - blog-postgres
      - blog-redis
      - blog-queue-redis
      - storage
      - mailer
      - centrifugo
  blog-queue-worker:
    build:
      context: ./blog/docker/development
      dockerfile: php-cli.docker
    volumes:
      - ./blog:/app
      - composer:/root/.composer/cache
    depends_on:
      - blog-postgres
      - blog-redis
      - blog-queue-redis
      - storage
      - mailer
      - centrifugo
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && php bin/console messenger:consume async -vv"
  blog-node-watch:
    image: node:12.7-alpine
    volumes:
      - ./blog:/app
    working_dir: /app
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"
  blog-node:
    image: node:12.7-alpine
    volumes:
      - ./blog:/app
    working_dir: /app
  blog-postgres:
    image: postgres:11.2-alpine
    volumes:
      - blog-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54321:5432"
  blog-redis:
    image: redis:5.0-alpine
    volumes:
      - blog-redis:/data
    command:
      - 'redis-server'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--requirepass secret'
  blog-queue-redis:
    image: redis:5.0-alpine
    volumes:
      - blog-queue-redis:/data

  storage:
    build:
      context: ./storage/docker/development
      dockerfile: nginx.docker
    volumes:
      - ./storage:/app
    ports:
      - "8081:80"
  storage-ftp:
    image: stilliard/pure-ftpd
    environment:
      FTP_USER_NAME: app
      FTP_USER_PASS: secret
      FTP_USER_HOME: /app
    volumes:
      - ./storage/public:/app

  mailer:
    image: mailhog/mailhog
    ports:
      - "8082:8025"

  centrifugo:
    image: centrifugo/centrifugo:v2.2
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      CENTRIFUGO_SECRET: secret
      CENTRIFUGO_API_KEY: secret
    volumes:
      - ./centrifugo/docker/development/centrifugo:/centrifugo
    ports:
      - "8083:8000"
    command: centrifugo --admin --admin_insecure

volumes:
  blog-postgres:
  blog-redis:
  blog-queue-redis:
  composer: